# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: bekarys.rakhymbek@gmail.com
author_name: Bekarys2323322332
preset_name: starter
project_name: SOSA-frontend

