# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: bekarys.rakhymbek@gmail.com
author_name: Bekarys2323322332
contract_name: invest_inus
deployment_language: python
preset_name: starter
project_name: SOSA-contracts

